name: Deploy to GCP E2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to E2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          # Create app directory if it doesn't exist
          cd ~/hass.agent-bot
        
          # Or if directory already exists:
          git pull origin main
          
          # Build and start containers
          sudo docker-compose build
          sudo docker-compose up -d